name: CI/CD Medallion Breweries

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:

  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install flake8 pytest pyspark

      - name: Lint transformations
        run: |
          flake8 medallion_dlt_breweries/medallion_dlt_breweries_bronze_silver/transformations/ \
            --max-line-length=120 \
            --extend-ignore=F401,F403,F405,E111,W293,W292,E302,E303,E251,E114,E303 \
            || true
          flake8 medallion_dlt_breweries/medallion_dlt_breweries_silver_gold/transformations/ \
            --max-line-length=120 \
            --extend-ignore=F401,F403,F405,E111,W293,W292,E302,E303,E251,E114,E303 \
            || true

      - name: Run tests
        run: pytest tests/ -v || true

  cd:
      
    needs: ci
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4.2.2
  
      - name: Install Databricks CLI
        run: curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
  
      - name: Trigger Job Databricks
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: databricks jobs run-now --job-id ${{ secrets.DATABRICKS_JOB_ID }}
